name: central-sm-cp
version: v2.4
controlPlaneNamespace: istio-system
gateways:
  egress:
    enables: false
bookinfoHost: bookinfo-istio.apps.foster-rosa.hr9c.p1.openshiftapps.com
httpdHost: httpd-istio.apps.foster-rosa.hr9c.p1.openshiftapps.com