apiVersion: v1
data:
  insecure: dHJ1ZQ==
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL01PQkItUEYvcGF5bWVudHMtZ2l0b3Bz
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-3728261057
  namespace: openshift-gitops
type: Opaque
---
apiVersion: v1
data:
  name: aGVsbQ==
  password: Z2l0aHViX3BhdF8xMUFaUlNGUEEwOVVZVkxIR2hMTGNIX0R3UmJlU1RSaHRNUll6ZklNWHlNd1JDdVNhR1NUclFUUTBUaGFJUG1ZTXBUTFJPWUpOVlFjWW5jbFNV
  project: ZGVmYXVsdA==
  type: aGVsbQ==
  url: aHR0cHM6Ly9tb2JiLXBmLmdpdGh1Yi5pby9oZWxtLXJlcG9zaXRvcnkv
  username: IGZvc3Rlci1yaA==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-3956390023
  namespace: openshift-gitops
type: Opaque