---
{{ $c := . }}
{{ range .Values.subscriptions }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $c.Release.Namespace }}
  labels:
    {{- include "operatorhub.labels" $c | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
spec:
  channel: {{ .channel }}
  name: {{ .name }}
  installPlanApproval: {{ .installPlanApproval }}
  source: {{ .source }}
  sourceNamespace: {{ .sourceNamespace | default $c.Release.Namespace }}
{{ end }}
---
{{ $c := . }}
{{ range .Values.operatorGroups }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $c.Release.Namespace }}
  labels:
    {{- include "operatorhub.labels" $c | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
spec:
  {{- if not (eq (.targetNamespace | default "") "all") }}
  targetNamespaces:
  - {{ .targetNamespace | default $c.Release.Namespace }}
  {{- end }}
{{ end }}
---
{{ $c := . }}
{{ range .Values.catalogSources }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $c.Release.Namespace }}
  labels:
    {{- include "operatorhub.labels" $c | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
spec:
  sourceType: {{ .sourceType }}
  image: {{ .image }}
  displayName: {{ .displayName }}
  publisher: {{ .publisher }}
{{ end }}
---

  - name: openshift-gitops-operator
    channel: latest
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  - name: openshift-pipelines-operator
    channel: latest
    installPlanApproval: Automatic
    source: redhat-operators 
    sourceNamespace: openshift-marketplace 
  - name: kiali-ossm
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  - name: elasticsearch-operator
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  - name: servicemeshoperator
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  - name: jaeger-product
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  - name: 
    channel: 
    installPlanApproval: 
    source: 
    sourceNamespace: 
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
  labels:
    operators.coreos.com/openshift-cert-manager-operator.cert-manager-operator: ""
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
  - name: 
    channel: 
    installPlanApproval: 
    source: 
    sourceNamespace: 
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    helm.sh/hook: pre-install
    olm.providedAPIs: CertManager.v1alpha1.operator.openshift.io,Certificate.v1.cert-manager.io,CertificateRequest.v1.cert-manager.io,Challenge.v1.acme.cert-manager.io,ClusterIssuer.v1.cert-manager.io,Issuer.v1.cert-manager.io,Order.v1.acme.cert-manager.io
  generateName: cert-manager-operator-
  name: cert-manager-operator-j92kc
  namespace: cert-manager-operator
spec:
  targetNamespaces:
  - cert-manager-operator
---
  - name: 
    channel: 
    installPlanApproval: 
    source: 
    sourceNamespace: 
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    helm.sh/hook: pre-install
  labels:
    operators.coreos.com/external-secrets-operator.openshift-operators: ""
  name: external-secrets-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
---
  - name: 
    channel: 
    installPlanApproval: 
    source: 
    sourceNamespace: 
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    helm.sh/hook: pre-install
  labels:
    operators.coreos.com/rhacs-operator.rhacs-operator: ""
  name: rhacs-operator
  namespace: rhacs-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
  - name: 
    channel: 
    installPlanApproval: 
    source: 
    sourceNamespace: 
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    helm.sh/hook: pre-install
    olm.providedAPIs: Central.v1alpha1.platform.stackrox.io,SecuredCluster.v1alpha1.platform.stackrox.io
  generateName: rhacs-operator-
  name: rhacs-operator-jxmx6
  namespace: rhacs-operator
spec:
  upgradeStrategy: Default
---
