---
{{ $c := . }}
{{ range .Values.subscriptions }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $c.Release.Namespace }}
  labels:
    {{- include "operatorhub.labels" $c | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
spec:
  channel: {{ .channel }}
  name: {{ .name }}
  installPlanApproval: {{ .installPlanApproval }}
  source: {{ .source }}
  sourceNamespace: {{ .sourceNamespace | default $c.Release.Namespace }}
{{ end }}
---
{{ $c := . }}
{{ range .Values.operatorGroups }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $c.Release.Namespace }}
  labels:
    {{- include "operatorhub.labels" $c | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
spec:
  {{- if not (eq (.targetNamespace | default "") "all") }}
  targetNamespaces:
  - {{ .targetNamespace | default $c.Release.Namespace }}
  {{- end }}
{{ end }}
---
# {{ $c := . }}
# {{ range .Values.catalogSources }}
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: CatalogSource
# metadata:
#   name: {{ .name }}
#   namespace: {{ .namespace | default $c.Release.Namespace }}
#   labels:
#     {{- include "operatorhub.labels" $c | nindent 4 }}
#   annotations:
#     helm.sh/hook: pre-install
# spec:
#   sourceType: {{ .sourceType }}
#   image: {{ .image }}
#   displayName: {{ .displayName }}
#   publisher: {{ .publisher }}
# {{ end }}
# ---



