apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "1"
    deployment.kubernetes.io/revision: "3"
  generation: 3
  labels:
    app: httpd
  name: httpd-istio
  namespace: httpd-istio
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: httpd
    spec:
      containers:
      - image: quay.io/centos7/httpd-24-centos7
        imagePullPolicy: Always
        name: httpd-24-centos7
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd
  name: httpd
  namespace: httpd-istio
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "2"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpd
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "3"
  name: default
  namespace: httpd-istio
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpd-vs
  namespace: httpd-istio
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "3"
spec:
  hosts:
  - "{{ .Values.httpdHost }}"
  gateways:
  - {{.Values.controlPlaneNamespace}}/central-gateway
  http:
  - match:
    - uri:
        regex: "/*"
    route:
    - destination:
        host: httpd.httpd-istio.svc.cluster.local
        port:
          number: 80
